{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "efs-csi-plugin-addons.serviceAccountName" . }}
  labels:
    {{- include "efs-csi-plugin-addons.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-csi-allow-event-patch
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-csi-efs-csi-allow-event-patch-binding
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
subjects:
  - kind: ServiceAccount
    name: {{ include "efs-csi-plugin-addons.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: efs-csi-allow-event-patch
  apiGroup: rbac.authorization.k8s.io
{{- end }}
