{
 "title": "Core Signalsz",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "traces_spanmetrics_calls_total" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=~\"$application\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=~\"$application\",span_status=\"STATUS_CODE_ERROR\"}[$__rate_interval])) by (service)/sum(rate(traces_spanmetrics_calls_total{service=~\"$application\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=~\"$application\"}[$__rate_interval])) by (span_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(traces_spanmetrics_duration_seconds_sum{service=~\"$application\"}[1m])) \n/ sum by (service) (rate(traces_spanmetrics_calls_total{service=~\"$application\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_duration_seconds_bucket{service=~\"$application\",le!=\"+Inf\"}) by (le) ",
     "legendFormat": "{{le}} sec"
    }
   ]
  }
 ]
}